### PR TITLE
fix for use with atom-shell 0.20.3

### PR DESCRIPTION
**Pull request by ttilley**
make use of the new GYP_DEFINES method of setting project/product names
fix a small typo in atom.gyp if found; bug only effects mac users
fixes issue #7

### CODE REVIEW

**Comment by paulcbetts** [comment]
@ttilley Can you fix the typo in Atom Shell itself too?

**Comment by ttilley** [comment]
added https://github.com/atom/atom-shell/pull/966 for the typo

**Comment by unindented** [comment]
The fix was merged into `atom-shell` some days ago. @paulcbetts can we get this merged here too please?

**Comment by paulcbetts** [comment]
@unindented On it :) Gonna update atom-shell-starter too

**Comment by unindented** [comment]
Aaaawesome

**Comment by unindented** [comment]
Could we get a version bump in this project, to make use of the awesomeness?

**Comment by paulcbetts** [comment]
Already done!

**Comment by unindented** [comment]
Ah sorry, I was looking here instead of npm. I already see 1.1.5. Thank you!

**Pull request merged**
